version: '3'
services:
  my-node-server:
    image: krishna/node-server-1
    ports:
       - "3000:3000"
  envoy:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: envoy/local
    ports:
      - "8080:8080"